@extends('layouts.admin')
@section('title','Historique des paiements')
@section('page_title','Historique paiement')
@section('breadcrumb','Paiements étudiants / Historique')
@push('styles')
<style>
.ph-page{display:flex;flex-direction:column;gap:20px}.ph-head{display:flex;justify-content:space-between;gap:18px;padding:25px;border:1px solid var(--ap-border);border-radius:20px;background:linear-gradient(135deg,rgba(18,30,51,.98),rgba(10,18,32,.95))}.ph-head h2{margin:0 0 5px;color:#fff}.ph-head p{margin:0;color:var(--ap-muted)}.ph-actions{display:flex;gap:9px;align-items:flex-start}.ph-btn{display:inline-flex;align-items:center;gap:7px;min-height:42px;padding:0 14px;border:1px solid var(--ap-border);border-radius:10px;background:rgba(255,255,255,.04);color:#dbeafe;text-decoration:none;font-weight:750;font-size:.75rem}.ph-btn.primary{background:linear-gradient(135deg,#2563eb,#6d28d9);color:#fff;border:0}.ph-current{padding:20px;border:1px solid var(--ap-border);border-radius:18px;background:rgba(12,21,37,.94)}.ph-current h3{margin:0 0 13px;color:#fff;font-size:1rem}.ph-current-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.ph-current-item{padding:13px;border:1px solid var(--ap-border);border-radius:12px;background:rgba(255,255,255,.025)}.ph-current-item span,.ph-current-item strong{display:block}.ph-current-item span{color:#718096;font-size:.68rem}.ph-current-item strong{margin-top:5px;color:#e2e8f0}.ph-panel{overflow:hidden;border:1px solid var(--ap-border);border-radius:20px;background:rgba(12,21,37,.94)}.ph-table-wrap{overflow-x:auto}.ph-table{width:100%;min-width:900px;border-collapse:collapse}.ph-table th{padding:13px 15px;text-align:left;color:#8291a8;font-size:.67rem;text-transform:uppercase}.ph-table td{padding:15px;border-top:1px solid rgba(148,163,184,.09);color:#cbd5e1;font-size:.75rem}.ph-badge{display:inline-flex;padding:6px 9px;border-radius:999px;font-weight:750;font-size:.68rem}.ph-badge.green{color:#86efac;background:rgba(34,197,94,.09)}.ph-badge.gray{color:#94a3b8;background:rgba(148,163,184,.07)}.ph-cancel{border:1px solid rgba(239,68,68,.18);border-radius:8px;background:rgba(239,68,68,.07);color:#fca5a5;padding:7px 9px}@media(max-width:800px){.ph-head{flex-direction:column}.ph-current-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.ph-current-grid{grid-template-columns:1fr}.ph-actions{flex-direction:column}.ph-btn{width:100%;justify-content:center}}
</style>
@endpush
@section('content')
<div class="ph-page">
    <section class="ph-head"><div><h2>{{ $student->name }}</h2><p>{{ $student->email }} — Historique complet des paiements</p></div><div class="ph-actions"><a class="ph-btn" href="{{ route('admin.student-payments.index') }}"><i class="bi bi-arrow-left"></i> Liste</a><a class="ph-btn primary" href="{{ route('admin.student-payments.create',['student'=>$student->id]) }}"><i class="bi bi-plus-circle"></i> Nouveau paiement</a></div></section>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <section class="ph-current"><h3>Paiement actuel</h3>@if($currentPayment)<div class="ph-current-grid"><div class="ph-current-item"><span>Statut</span><strong style="color:#86efac">Payé</strong></div><div class="ph-current-item"><span>Formule</span><strong>{{ $currentPayment->plan_label }}</strong></div><div class="ph-current-item"><span>Début</span><strong>{{ $currentPayment->starts_at->format('d/m/Y') }}</strong></div><div class="ph-current-item"><span>Expiration</span><strong>{{ $currentPayment->expires_at->format('d/m/Y') }}</strong></div></div>@else<p style="margin:0;color:#fca5a5">Aucun paiement valide actuellement.</p>@endif</section>
    <section class="ph-panel"><div class="ph-table-wrap"><table class="ph-table"><thead><tr><th>Date</th><th>Formule</th><th>Période</th><th>Montant</th><th>Mode</th><th>Statut</th><th>Ajouté par</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ optional($payment->paid_at)->format('d/m/Y') }}</td><td>{{ $payment->plan_label }}</td><td>{{ $payment->starts_at->format('d/m/Y') }} → {{ $payment->expires_at->format('d/m/Y') }}</td><td>{{ $payment->amount !== null ? number_format((float)$payment->amount,2,',',' ') . ' DH' : '—' }}</td><td>{{ $payment->payment_method_label }}</td><td>@if($payment->status==='paid')<span class="ph-badge green">Payé</span>@else<span class="ph-badge gray">Annulé</span>@endif</td><td>{{ optional($payment->creator)->name ?? 'Admin' }}</td><td>@if($payment->status==='paid')<form method="POST" action="{{ route('admin.student-payments.cancel',$payment) }}" onsubmit="return confirm('Annuler ce paiement ? L’historique sera conservé.')">@csrf @method('PATCH')<button class="ph-cancel" type="submit" title="Annuler"><i class="bi bi-x-lg"></i></button></form>@endif</td></tr>@empty<tr><td colspan="8" style="text-align:center;padding:35px;color:#64748b">Aucun paiement enregistré pour cet étudiant.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
